# Generated by Django 4.2.3 on 2023-07-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
