# Generated by Django 4.2.3 on 2023-07-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
